#!/bin/sh

# $1 is the state (pre/post), $2 is the action (suspend/hibernate)
# /usr/lib/systemd/system-sleep/, chmod  +x
case "$1" in
    pre)
        # /usr/sbin/modprobe -r brcmfmac_wcc
        # /usr/sbin/modprobe -r brcmfmac
        /usr/sbin/modprobe -r facetimehd
        for i in 1 2 3 4 5 6 7; do
            echo 0 > /sys/devices/system/cpu/cpu$i/online || true
        done
        ;;
    post)
        for i in 1 2 3 4 5 6 7; do
            echo 1 > /sys/devices/system/cpu/cpu$i/online || true
        done
        # /usr/sbin/modprobe brcmfmac
        /usr/sbin/modprobe facetimehd
        ;;
esac
